image: openjdk:18-jdk-alpine

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - ./mvnw verify --file pom.xml
            caches:
              - maven
            services:
              - mongo
            after-script:
              - pipe: atlassian/checkstyle-report:0.3.0
                variables:
                  DEBUG: "true"
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
definitions:
  services:
    mongo:
      image: mongo