version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    container_name: frontend
    ports:
      - "3001:3001"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
